name: st2-docker

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:

jobs:
  docker-compose-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker-compose lint check
        run: docker-compose config

  docker-compose-up:
    runs-on: ubuntu-latest
    needs: [docker-compose-lint]
    steps:
      - uses: actions/checkout@v3

      - name: Pull Docker Images
        run: |
          docker-compose pull

      - name: Start st2 with docker-compose
        run: |
          docker-compose up --detach

      - name: Sleep
        run: |
          sleep 60

      - name: Run st2 smoke-tests
        run: |
          docker-compose --file tests/st2tests.yaml run st2test

      - name: Troubleshooting the build failure
        if: ${{ failure() }}
        run: |
          docker-compose ps
          # Display logs to help troubleshoot build failures, etc
          docker-compose logs --tail="500" st2api
          exit 1
